### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../output/CDR_CHED_2019-01-04_23-04-44-639986/000_train.txt_conll_evaluation.txt'

### ISSUE THREAD

**Issue by ghost** [BaderLab/Transfer-Learning-BNER-Bioinformatics-2018#1]
Hi,

I get the above error when I use baseline config with NeuroNER with word2vec wiki-pubmed-pmc.txt embeddings. However, it works fine when I test NeuroNER with Glove embeddings. Do you have any idea why the evaluation file is not being written in the output folder?

**Comment by JohnGiorgi** [comment]
Hi @BuggyLife

Will you try reading through [this](https://github.com/Franck-Dernoncourt/NeuroNER/issues/34) issue on the NeuroNER repo and see if it helps you fix the problem? They are basically two suggestions:

1. Make sure perl is installed (run `perl -v` at your command line)
2. Increasing swap file size

If neither of those help, let me know and I will get more details off you in order to recreate the error. Thanks!

**Comment by ghost** [comment]
Hi @JohnGiorgi 

1. I have Perl installed already 
perl -v 
This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi
(with 69 registered patches, see perl -V for more detail)

Copyright 1987-2015, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.


2. I already have 7.9G for swap file, can you suggest how much do I increase it?
sudo swapon --show
NAME      TYPE      SIZE USED PRIO
/dev/sda5 partition 7.9G   0B   -1

**Comment by JohnGiorgi** [comment]
@BuggyLife 

Hmm, I imagine 7.9Gb is enough and you already have Perl installed, so something else must be going wrong.

I am going to try to re-create the error. You said you are using the `baseline.ini` config with `wiki-pubmed-pmc.txt `embeddings. It looks like you are using the `CDR_CHED` dataset.

I will run NeuroNER with those inputs and see if I can reproduce the error first. Then I will try to get back to you with a fix.

**Comment by ghost** [comment]
Yes exactly I am using the said configurations.

**Comment by JohnGiorgi** [comment]
@BuggyLife Hi, sorry this is taking me a long time to get to. If you are still stuck on it, will you try opening an issue on the [NeuroNER](https://github.com/Franck-Dernoncourt/NeuroNER) repo?

This looks to be a NeuroNER specific issue.

**Comment by ghost** [comment]
Hi, 

Ok I'll do that. I just wanted to be sure about the data, CDR CHED is the data that contains only chemical annotations and CDR_DISO contains disease mentions, and both of them are from original CDR corpus?

Or have you combined the three corpora for chemical NER (Biosemantic, CDR, CHEMDNER)?

**Comment by JohnGiorgi** [comment]
The former! CDR contains annotations for diseases and chemicals. That was broken up in our study into two copora (one annotated for chemicals and one annotated for disease). Biosemantic and  Chemdner are their own corpora.

Note that you can get some of the above mentioned datasets [here](https://github.com/cambridgeltl/MTL-Bioinformatics-2016/tree/master/data). Just note that CDR is named BC5CDR. Also we used the IOB tag set in our study.

**Comment by ghost** [comment]
so there are two CHEMDNER datasets in Habibi et al paper and you have used CHEMDNER patent only. The link that you have given for the datsets in your last comment has only one BC4CHEMD data, is that CHEMDNER patent or CHEMDNER scientific article?

If it's scientific articles, where do I get the patent CHEMDNER dataset, the one that you have used in your study? I am asking because I am writing a paper and need to do comparisons.

**Comment by JohnGiorgi** [comment]
The CHEMDNER patent corpus is linked to from the table in the README of this repository. [Here](https://biocreative.bioinformatics.udel.edu/resources/corpora/chemdner-patents-cemp-corpus/) it is again for convenience. You will need to create a BioCreative account in order to download it.

Once you make an account and are able to log in, the above link will bring you to a page where you can download multiple files. I used `CEMP development set v03` and `CEMP training set` to form a single corpus which I then split into train/test/valid pairs. Judging on the number of annotations the [Habibi et al](https://academic.oup.com/bioinformatics/article/33/14/i37/3953940) paper states for the CHEMDNER patent corpus, I reckon they did the same thing.

It requires some processing, however, to get it into valid Standoff format for use with NeuroNER. Let me know if you get stuck here and I can help (I used to have a script for doing it but I can't seem to track it down).

**Comment by ghost** [comment]
How about you directly email me the corpus?as I want to be on the same grounds in order to not draw any misleading/false conclusions? This is a request.

**Comment by gbader** [comment]
The click through license of BioCreative is as follows:

"By registering the user agrees to use any data available from this site exclusively for scientific purposes and/or non-commercial purposes and will not redistribute this data or any parts thereof. The provided data is available only for text mining parties and educational purposes."

This is why we're not redistributing the corpus.

Gary

**Comment by ghost** [comment]
Ah okay. Thanks anyways.

**Comment by ghost** [comment]
> The CHEMDNER patent corpus is linked to from the table in the README of this repository. [Here](https://biocreative.bioinformatics.udel.edu/resources/corpora/chemdner-patents-cemp-corpus/) it is again for convenience. You will need to create a BioCreative account in order to download it.
> 
> Once you make an account and are able to log in, the above link will bring you to a page where you can download multiple files. I used `CEMP development set v03` and `CEMP training set` to form a single corpus which I then split into train/test/valid pairs. Judging on the number of annotations the [Habibi et al](https://academic.oup.com/bioinformatics/article/33/14/i37/3953940) paper states for the CHEMDNER patent corpus, I reckon they did the same thing.
> 
> It requires some processing, however, to get it into valid Standoff format for use with NeuroNER. Let me know if you get stuck here and I can help (I used to have a script for doing it but I can't seem to track it down).



> The CHEMDNER patent corpus is linked to from the table in the README of this repository. [Here](https://biocreative.bioinformatics.udel.edu/resources/corpora/chemdner-patents-cemp-corpus/) it is again for convenience. You will need to create a BioCreative account in order to download it.
> 
> Once you make an account and are able to log in, the above link will bring you to a page where you can download multiple files. I used `CEMP development set v03` and `CEMP training set` to form a single corpus which I then split into train/test/valid pairs. Judging on the number of annotations the [Habibi et al](https://academic.oup.com/bioinformatics/article/33/14/i37/3953940) paper states for the CHEMDNER patent corpus, I reckon they did the same thing.
> 
> It requires some processing, however, to get it into valid Standoff format for use with NeuroNER. Let me know if you get stuck here and I can help (I used to have a script for doing it but I can't seem to track it down).

Hi,

I have downloaded the corpus. what pre-processing needs to be done?

**Comment by JohnGiorgi** [comment]
You need to get the corpus into the [brat standoff format](http://brat.nlplab.org/standoff.html) or a CoNLL-like format (see [this repo](https://github.com/cambridgeltl/MTL-Bioinformatics-2016/tree/master/data) for examples). Either can then be used with NeuroNER for training.

**Comment by ghost** [comment]
Hi, I have managed to get the script for data conversion.
So NeuroNER only detects the chemical entity or does it further classify into subtypes(family, abbreviation, formula etc)?

**Comment by JohnGiorgi** [comment]
Hi, 

NeuroNER will detect whatever labels it is trained on. For example, if your dataset contained only one tag, say “CHED” that would be the only tag NeuroNER would be able to detect (after training).

Maybe if you show me a snippet of your converted dataset I can more directly answer your question?

**Comment by BuggyLife** [comment]
Sure. Here it is,

> Antiviral	O	0	9	CA2120743C	T	true
acyclic	B-FAMILY	10	17	CA2120743C	T	true
phosphonomethoxyalkyl	I-FAMILY	18	39	CA2120743C	T	true
substituted	O	40	51	CA2120743C	T	true
,	O	51	52	CA2120743C	T	false
alkenyl	B-MULTIPLE	53	60	CA2120743C	T	true
and	I-MULTIPLE	61	64	CA2120743C	T	true
alkynyl	I-MULTIPLE	65	72	CA2120743C	T	true
purine	I-MULTIPLE	73	79	CA2120743C	T	true
and	I-MULTIPLE	80	83	CA2120743C	T	true
pyrimidine	I-MULTIPLE	84	94	CA2120743C	T	true
derivatives	O	95	106	CA2120743C	T	true
.	O	106	107	CA2120743C	T	false

Disclosed	O	0	9	CA2120743C	A	true
are	O	10	13	CA2120743C	A	true
acyclic	B-FAMILY	14	21	CA2120743C	A	true
phosphonomethoxyalkyl	I-FAMILY	22	43	CA2120743C	A	true
substituted	O	44	55	CA2120743C	A	true
,	O	55	56	CA2120743C	A	false
alkenyl	B-MULTIPLE	57	64	CA2120743C	A	true
and	I-MULTIPLE	65	68	CA2120743C	A	true
alkynyl	I-MULTIPLE	69	76	CA2120743C	A	true
purine	I-MULTIPLE	77	83	CA2120743C	A	true
and	I-MULTIPLE	84	87	CA2120743C	A	true
pyrimidine	I-MULTIPLE	88	98	CA2120743C	A	true
derivatives	O	99	110	CA2120743C	A	true
and	O	111	114	CA2120743C	A	true
a	O	115	116	CA2120743C	A	true
pharmaceutical	O	117	131	CA2120743C	A	true
composition	O	132	143	CA2120743C	A	true
comprising	O	144	154	CA2120743C	A	true
said	O	155	159	CA2120743C	A	true
purine	B-FAMILY	160	166	CA2120743C	A	true
and	O	167	170	CA2120743C	A	true
pyrimidine	B-FAMILY	171	181	CA2120743C	A	true
derivatives	O	182	193	CA2120743C	A	true
.	O	193	194	CA2120743C	A	false

The	O	195	198	CA2120743C	A	true
compounds	O	199	208	CA2120743C	A	true
are	O	209	212	CA2120743C	A	true
useful	O	213	219	CA2120743C	A	true
in	O	220	222	CA2120743C	A	true
the	O	223	226	CA2120743C	A	true
treatment	O	227	236	CA2120743C	A	true
of	O	237	239	CA2120743C	A	true
viral	O	240	245	CA2120743C	A	true
infections	O	246	256	CA2120743C	A	true
,	O	256	257	CA2120743C	A	false
especially	O	258	268	CA2120743C	A	true
those	O	269	274	CA2120743C	A	true
caused	O	275	281	CA2120743C	A	true
by	O	282	284	CA2120743C	A	true
human	O	285	290	CA2120743C	A	true
immunodeficiency	O	291	307	CA2120743C	A	true
virus	O	308	313	CA2120743C	A	true
(	O	314	315	CA2120743C	A	true
HIV	O	315	318	CA2120743C	A	false
)	O	318	319	CA2120743C	A	false
.	O	319	320	CA2120743C	A	false

Injection	O	0	9	CA2142445C	T	true
solutions	O	10	19	CA2142445C	T	true
of	O	20	22	CA2142445C	T	true
azosemide	B-TRIVIAL	23	32	CA2142445C	T	true
which	O	33	38	CA2142445C	T	true
are	O	39	42	CA2142445C	T	true
ready	O	43	48	CA2142445C	T	true
for	O	49	52	CA2142445C	T	true
injection	O	53	62	CA2142445C	T	true
.	O	62	63	CA2142445C	T	false

Aqueous	O	0	7	CA2142445C	A	true
injection	O	8	17	CA2142445C	A	true
solution	O	18	26	CA2142445C	A	true
that	O	27	31	CA2142445C	A	true
is	O	32	34	CA2142445C	A	true
ready	O	35	40	CA2142445C	A	true
-	O	40	41	CA2142445C	A	false
for	O	41	44	CA2142445C	A	false
-	O	44	45	CA2142445C	A	false
injection	O	45	54	CA2142445C	A	false
of	O	55	57	CA2142445C	A	true
a	O	58	59	CA2142445C	A	true
water	O	60	65	CA2142445C	A	true
-	O	65	66	CA2142445C	A	false
soluble	O	66	73	CA2142445C	A	false
,	O	73	74	CA2142445C	A	false
physiologically	O	75	90	CA2142445C	A	true
well	O	91	95	CA2142445C	A	true
-	O	95	96	CA2142445C	A	false
tolerated	O	96	105	CA2142445C	A	false
azosemide	B-TRIVIAL	106	115	CA2142445C	A	true
salt	O	116	120	CA2142445C	A	true
of	O	121	123	CA2142445C	A	true
an	O	124	126	CA2142445C	A	true
organic	O	127	134	CA2142445C	A	true
amide	B-FAMILY	135	140	CA2142445C	A	true
,	O	140	141	CA2142445C	A	false
which	O	142	147	CA2142445C	A	true
contains	O	148	156	CA2142445C	A	true
an	O	157	159	CA2142445C	A	true
organic	O	160	167	CA2142445C	A	true
solvent	O	168	175	CA2142445C	A	true
and	O	176	179	CA2142445C	A	true
if	O	180	182	CA2142445C	A	true
desired	O	183	190	CA2142445C	A	true
,	O	190	191	CA2142445C	A	false
a	O	192	193	CA2142445C	A	true
physiologically	O	194	209	CA2142445C	A	true
well	O	210	214	CA2142445C	A	true
-	O	214	215	CA2142445C	A	false
tolerated	O	215	224	CA2142445C	A	false
buffer	O	225	231	CA2142445C	A	true
and	O	232	235	CA2142445C	A	true
it	O	236	238	CA2142445C	A	true
concerns	O	239	247	CA2142445C	A	true
a	O	248	249	CA2142445C	A	true
process	O	250	257	CA2142445C	A	true
for	O	258	261	CA2142445C	A	true
the	O	262	265	CA2142445C	A	true
production	O	266	276	CA2142445C	A	true
of	O	277	279	CA2142445C	A	true
such	O	280	284	CA2142445C	A	true
an	O	285	287	CA2142445C	A	true
injection	O	288	297	CA2142445C	A	true
solution	O	298	306	CA2142445C	A	true
in	O	307	309	CA2142445C	A	true
which	O	310	315	CA2142445C	A	true
the	O	316	319	CA2142445C	A	true
salt	O	320	324	CA2142445C	A	true
is	O	325	327	CA2142445C	A	true
dissolved	O	328	337	CA2142445C	A	true
in	O	338	340	CA2142445C	A	true
a	O	341	342	CA2142445C	A	true
mixture	O	343	350	CA2142445C	A	true
which	O	351	356	CA2142445C	A	true
contains	O	357	365	CA2142445C	A	true
water	O	366	371	CA2142445C	A	true
,	O	371	372	CA2142445C	A	false
an	O	373	375	CA2142445C	A	true
organic	O	376	383	CA2142445C	A	true
solvent	O	384	391	CA2142445C	A	true
and	O	392	395	CA2142445C	A	true
,	O	395	396	CA2142445C	A	false
if	O	397	399	CA2142445C	A	true
desired	O	400	407	CA2142445C	A	true
,	O	407	408	CA2142445C	A	false
a	O	409	410	CA2142445C	A	true
physiologically	O	411	426	CA2142445C	A	true
well	O	427	431	CA2142445C	A	true
-	O	431	432	CA2142445C	A	false
tolerated	O	432	441	CA2142445C	A	false
buffer	O	442	448	CA2142445C	A	true
.	O	448	449	CA2142445C	A	false

Method	O	0	6	CA2143752C	T	true
of	O	7	9	CA2143752C	T	true
preventing	O	10	20	CA2143752C	T	true
nmda	O	21	25	CA2143752C	T	true
receptor	O	26	34	CA2143752C	T	true
-	O	34	35	CA2143752C	T	false
mediated	O	35	43	CA2143752C	T	false
neuronal	O	44	52	CA2143752C	T	true
damage	O	53	59	CA2143752C	T	true
.	O	59	60	CA2143752C	T	false

Disclosed	O	0	9	CA2143752C	A	true
is	O	10	12	CA2143752C	A	true
a	O	13	14	CA2143752C	A	true
method	O	15	21	CA2143752C	A	true
for	O	22	25	CA2143752C	A	true
reducing	O	26	34	CA2143752C	A	true
non	O	35	38	CA2143752C	A	true
-	O	38	39	CA2143752C	A	false
ischemic	O	39	47	CA2143752C	A	false
NMDA	O	48	52	CA2143752C	A	true
receptor	O	53	61	CA2143752C	A	true
-	O	61	62	CA2143752C	A	false
mediated	O	62	70	CA2143752C	A	false
neuronal	O	71	79	CA2143752C	A	true
damage	O	80	86	CA2143752C	A	true
in	O	87	89	CA2143752C	A	true
a	O	90	91	CA2143752C	A	true
mammal	O	92	98	CA2143752C	A	true
by	O	99	101	CA2143752C	A	true
administering	O	102	115	CA2143752C	A	true
to	O	116	118	CA2143752C	A	true
the	O	119	122	CA2143752C	A	true
mammal	O	123	129	CA2143752C	A	true
a	O	130	131	CA2143752C	A	true
compound	O	132	140	CA2143752C	A	true
of	O	141	143	CA2143752C	A	true
the	O	144	147	CA2143752C	A	true
formula	O	148	155	CA2143752C	A	true
shown	O	156	161	CA2143752C	A	true
in	O	162	164	CA2143752C	A	true
Fig	O	165	168	CA2143752C	A	true
.	O	168	169	CA2143752C	A	false
1	O	170	171	CA2143752C	A	true
(	O	172	173	CA2143752C	A	true
or	O	173	175	CA2143752C	A	false
a	O	176	177	CA2143752C	A	true
physiologically	O	178	193	CA2143752C	A	true
-	O	193	194	CA2143752C	A	false
acceptable	O	194	204	CA2143752C	A	false
salt	O	205	209	CA2143752C	A	true
thereof	O	210	217	CA2143752C	A	true
)	O	217	218	CA2143752C	A	false
,	O	218	219	CA2143752C	A	false
wherein	O	220	227	CA2143752C	A	true
R1	O	228	230	CA2143752C	A	true
includes	O	231	239	CA2143752C	A	true
an	O	240	242	CA2143752C	A	true
amino	B-SYSTEMATIC	243	248	CA2143752C	A	true
group	O	249	254	CA2143752C	A	true
,	O	254	255	CA2143752C	A	false
R2	O	256	258	CA2143752C	A	true
-	O	258	259	CA2143752C	A	false
R17	O	259	262	CA2143752C	A	false
are	O	263	266	CA2143752C	A	true
independently	O	267	280	CA2143752C	A	true
H	B-FORMULA	281	282	CA2143752C	A	true

**Comment by ghost** [comment]
Sure, here it is

```
Antiviral	O	0	9	CA2120743C	T	true
acyclic	B-FAMILY	10	17	CA2120743C	T	true
phosphonomethoxyalkyl	I-FAMILY	18	39	CA2120743C	T	true
substituted	O	40	51	CA2120743C	T	true
,	O	51	52	CA2120743C	T	false
alkenyl	B-MULTIPLE	53	60	CA2120743C	T	true
and	I-MULTIPLE	61	64	CA2120743C	T	true
alkynyl	I-MULTIPLE	65	72	CA2120743C	T	true
purine	I-MULTIPLE	73	79	CA2120743C	T	true
and	I-MULTIPLE	80	83	CA2120743C	T	true
pyrimidine	I-MULTIPLE	84	94	CA2120743C	T	true
derivatives	O	95	106	CA2120743C	T	true
.	O	106	107	CA2120743C	T	false
```

**Comment by JohnGiorgi** [comment]
Your labels are given in the second column in the snippet you posted. So NeuroNER is going to learn to predict those labels during training (e.g. FAMILY, MULTIPLE).

Note that in our study, we combined all labels in the chemical entity corpora under a single label, `CHED`.

**Comment by ghost** [comment]
> The CHEMDNER patent corpus is linked to from the table in the README of this repository. [Here](https://biocreative.bioinformatics.udel.edu/resources/corpora/chemdner-patents-cemp-corpus/) it is again for convenience. You will need to create a BioCreative account in order to download it.
> 
> Once you make an account and are able to log in, the above link will bring you to a page where you can download multiple files. I used `CEMP development set v03` and `CEMP training set` to form a single corpus which I then split into train/test/valid pairs. Judging on the number of annotations the [Habibi et al](https://academic.oup.com/bioinformatics/article/33/14/i37/3953940) paper states for the CHEMDNER patent corpus, I reckon they did the same thing.
> 
> It requires some processing, however, to get it into valid Standoff format for use with NeuroNER. Let me know if you get stuck here and I can help (I used to have a script for doing it but I can't seem to track it down).

Hi,

Can you please let me know the number of abstracts you have used for train, test and valid set?

**Comment by JohnGiorgi** [comment]
Hi, 

As stated in the paper, we used train/valid/test splits of 60%/10%/30% for all corpora. For the CHEMDNER patent corpus, that works out to 8400, 1400, and 4200 abstracts respectively.

Please let me know if this answers your question.
