### ISSUE TITLE
Query regarding pre-processing of Biosemantics corpus

### ISSUE THREAD

**Issue by ghost** [BaderLab/Transfer-Learning-BNER-Bioinformatics-2018#2]
Hi, 

Can you please explain about how you split the Biosemantics corpus? How many patents have you used in train/dev/test.?

**Comment by JohnGiorgi** [comment]
Hi, 

We used the "full set" obtained from [here](https://biosemantics.org/index.php/resources/chemical-patent-corpus) (as did Habibi et. al. it would appear) and split the corpus into train/valid/test sets of size 60%/10%/30%.

I have added a zip of three text files containing the exact filenames that were placed into each partition in this repo (accessible [here](https://github.com/BaderLab/Transfer-Learning-BNER-Bioinformatics-2018/blob/master/corpora/BioSemantics_partition_filenames.zip)).

Please let me know if this solves your issue.

**Comment by ghost** [comment]
Thanks!

**Comment by ghost** [comment]
hi,

had you discarded any of these tags?
"M" for IUPAC.
"I" for SMILES.
"Y" for InChi.
"D" for Trademark.
"B" for Abbreviation.
"C" for CAS number.
"F" for Formula.
"R" for Registry Number.
"G" for Generic.
"T" for Target.
"Disease" for Disease.
"MOA" for MOA.
"OCRERRORSPELL" for Spelling error.
"OCRERRORLINE" for Spurious line break.
