### ISSUE TITLE
ValueError: Tried to convert 'value' to a tensor and failed. Error: Cannot create a tensor proto whose content is larger than 2GB.

### ISSUE THREAD

**Issue by bluesea0** [BaderLab/Transfer-Learning-BNER-Bioinformatics-2018#4]
Hello, I try to run the baseline on NeuronNER with `token_pretrained_embedding_filepath = ./data/word_vectors/wikipedia-pubmed-and-PMC-w2v.txt`. And the word embedding text is 12.25GB. There is the error.
 `  File "/local/lib/python3.5/site-packages/neuroner/entity_lstm.py", line 361, in load_pretrained_token_embeddings
    sess.run(self.token_embedding_weights.assign(initial_weights))
  File "/local/lib/python3.5/site-packages/tensorflow/python/ops/variables.py", line 1762, in assign name=name)
ValueError: Tried to convert 'value' to a tensor and failed. Error: Cannot create a tensor proto whose content is larger than 2GB.`

Then I find one solution [https://stackoverflow.com/questions/35394103/initializing-tensorflow-variable-with-an-array-larger-than-2gb](url). 
However I don't know for sure whether I  should modify the source code in entity_lstm.py of NeuroNER. How to solve this problem？

**Comment by JohnGiorgi** [comment]
Hi, do you mind opening this issue (or seeing if a similar issue already exists) on the NeuroNER GitHub?

Just because this looks to be NeuroNER specific and not something wrong with our config file.

If you don’t get an answer there ping me again and I’ll take a closer look. Thanks!

**Comment by bluesea0** [comment]
Sorry to bother again. I made an issue of this error under NeuroNER 4 days ago, but there was no reply.

I use the baseline.ini file you provided. The error happens when the token embedding areassigned. 
I find that in dataset.py , line 155, of NeuroNER
```
        if parameters['token_pretrained_embedding_filepath'] != '':
            if token_to_vector==None:
                token_to_vector = utils_nlp.load_pretrained_token_embeddings(parameters)
```
It loads all words in the embedding file as the dataset. (the word embedding text is 12.25GB).
But Initializing tensorflow Variable with an array larger than 2GB can cause the above error.
Did have meet the same problem?  And have you ever changed the code or anything else?
Thank you.
